# -*- coding: utf-8 -*-
"""varquants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10S4xstBG49kpD_7T5hJK0qZsn04UhkME
"""

regioes_coleta = ['Centro', 'Zona Leste', 'Zona Norte', 'Zona Oeste', 'Zona Sul']
regioes_coleta

tipos_residuos = ['Orgânico', 'Perigoso', 'Reciclável', 'Rejeito']
tipos_residuos

origens_residuos = ['Comercial', 'Industrial', 'Residencial', 'Serviços de Saúde']
origens_residuos

metodos_destinacao = ['Aterro Sanitário', 'Compostagem', 'Incineração', 'Reciclagem']
metodos_destinacao