# -*- coding: utf-8 -*-
"""quali_var_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akNEDEwJirSzt3pJkyGSyCaUvlliouvf

Este notebook foi criado para importar a tabela de Resíduos Sólidos em Excel para o ambiente do Google Colab. Aqui mostraremos a importação da tabela, assim como a criação das tabelas.
"""

# Importação das bibliotecas que utilizaremos
import pandas as pd
import math

# Importação do arquivo de tabela a ser utilizado, através do path na seção "Files" do Colab, contendo as informações de resíduos sólidos
file='./Solid_waste_pt.xlsx'

# Visão geral da tabela
df=pd.read_excel(file)
df

# Tabela que mostra a quantidade de coletas realizadas em cada regiao
df_Regiao_Coleta=df.Regiao_Coleta.value_counts()
df_Regiao_Coleta

# Ordenação da tabela em ordem alfabética
df_Regiao_Coleta=df.Regiao_Coleta.value_counts().sort_index()
df_Regiao_Coleta

# Impressão do total das coletas realizadas
total_df_Regiao_Coleta=df_Regiao_Coleta.sum()
total_df_Regiao_Coleta

# Impressão da tabela com as Regiões de Coleta ordenadas de forma alfabética
dados_v_Regiao_Coleta=pd.DataFrame(df_Regiao_Coleta)
dados_v_Regiao_Coleta

# Reinicia os índices da região de coleta
dados_v_Regiao_Coleta=pd.DataFrame(df_Regiao_Coleta).reset_index()
# Renomeia as colunas na tabela com o total de resíduos coletados em cada região da cidade
dados_v_Regiao_Coleta.columns=['Região de Coleta','Total']
dados_v_Regiao_Coleta

print(dados_v_Regiao_Coleta)

# Cálculo da frequência relativa
dados_v_Regiao_Coleta['Frequência relativa(%)']=round((dados_v_Regiao_Coleta['Total']/total_df_Regiao_Coleta)*100,2)
print(dados_v_Regiao_Coleta)

# Criação de uma tabela com os dados de total de resíduos sólidos de cada região e a frequência relativa de porcentagem de cada região
tabela_Dados_v_Regiao_Coleta=pd.DataFrame(dados_v_Regiao_Coleta)
tabela_Dados_v_Regiao_Coleta

df_Tipo_Residuo=df.Tipo_Residuo.value_counts().sort_index()
df_Tipo_Residuo

df_Tipo_Residuo_Data_set=pd.DataFrame(df_Tipo_Residuo).reset_index()
df_Tipo_Residuo_Data_set.columns=['Tipo de Residuo','Total']
df_Tipo_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Tipo_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Tipo_Residuo_Data_set)

tabela_Tipo_Residuo=pd.DataFrame(df_Tipo_Residuo_Data_set)
tabela_Tipo_Residuo

df_Origem_Residuo=df.Origem_Residuo.value_counts().sort_index()
df_Origem_Residuo

df_Origem_Residuo_Data_set=pd.DataFrame(df_Origem_Residuo).reset_index()
df_Origem_Residuo_Data_set.columns=['Origem de Residuo','Total']
df_Origem_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Origem_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Origem_Residuo_Data_set)

tabela_Origem_Residuo=pd.DataFrame(df_Origem_Residuo_Data_set)
tabela_Origem_Residuo

df_Metodo_Destinacao=df.Metodo_Destinacao.value_counts().sort_index()
df_Metodo_Destinacao

df_Metodo_Destinacao_Data_set=pd.DataFrame(df_Metodo_Destinacao).reset_index()
df_Metodo_Destinacao_Data_set.columns=['Método de Destinação', 'Total']
df_Metodo_Destinacao_Data_set["Frequencia relativa(%)"]=round((df_Metodo_Destinacao_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Metodo_Destinacao_Data_set)

tabela_Metodo_Destinacao=pd.DataFrame(df_Metodo_Destinacao_Data_set)
tabela_Metodo_Destinacao